apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-cfg
data:
  jupyterhub_config.py: |
    from jupyterhub_traefik_proxy import TraefikTomlConfigmapProxy

    c.JupyterHub.proxy_class = TraefikTomlConfigmapProxy

    c.TraefikTomlConfigmapProxy.traefik_api_url = "http://traefik-ingress-service:8099"
    # traefik api endpoint login password
    c.TraefikTomlConfigmapProxy.traefik_api_password = "123"
    # traefik api endpoint login username
    c.TraefikTomlConfigmapProxy.traefik_api_username = "abc"

    c.TraefikTomlConfigmapProxy.cm_namespace = "proxy-poc"
    c.TraefikTomlConfigmapProxy.cm_name = "traefik-rules"
    c.TraefikTomlConfigmapProxy.in_cluster = True

    c.JupyterHub.services[0]['url'] = 'http://jupyterhub:8181'

  jupyterhub_admins: "admin"
  gpu_mode: ""
  singleuser_pvc_size: 2Gi
